name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Apps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use Node.js v20

      - name: Install dependencies
        run: npm ci --force

      # Build each app
      - name: Build Angular App
        run: |
          npx nx build angular-shop --prod --base-href=/e-shop/angular-shop/
          mv ./dist/apps/angular-shop/browser ./dist/apps/angular-shop-x
          rm -rf ./dist/apps/angular-shop
          mv ./dist/apps/angular-shop-x ./dist/apps/angular-shop

      - name: Build React App
        env:
          REACT_APP_API_URL: /e-shop/react-shop/
        run: npx nx build react-shop --prod

      - name: Build Vue App
        env:
          VUE_APP_API_URL: /e-shop/vue-shop/
        run: npx nx build vue-shop --prod

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/apps
